# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qEnacP75tVpuKumNPdtIY-GrTKu7T6O
"""

#from google.colab import files
#uploaded = files.upload()
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier


# קריאת שני הקבצים
file1 = "/content/Wednesday-workingHours.pcap_ISCX.csv"
file2 = "/content/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv"

data1 = pd.read_csv(file1)
data2 = pd.read_csv(file2)

data = pd.concat([data1, data2], ignore_index=True)

# ניקוי שמות עמודות
data.columns = data.columns.str.strip()

print("Number of rows before cleaning:", len(data))


# הפיכת התווית לבעיה בינארית:
# 0 = תקין
# 1 = מתקפה
data["Label"] = data["Label"].apply(
    lambda value: 0 if str(value).strip().upper() == "BENIGN" else 1
)


# ניקוי ערכים לא חוקיים
data.replace([np.inf, -np.inf], np.nan, inplace=True)
data.dropna(inplace=True)

print("Number of rows after cleaning:", len(data))


# הסרת עמודות לא רלוונטיות לפי המאמר
columns_to_remove = [
    "Bwd PSH Flags",
    "Bwd URG Flags",
    "Fwd Avg Bytes/Bulk",
    "Fwd Avg Packets/Bulk",
    "Fwd Avg Bulk Rate",
    "Bwd Avg Bytes/Bulk",
    "Bwd Avg Packets/Bulk",
    "Bwd Avg Bulk Rate"
]

data.drop(columns=[col for col in columns_to_remove if col in data.columns], inplace=True)


# שמונת המאפיינים שנבחרו במאמר
features = [
    "Fwd Packet Length Max",
    "Flow IAT Mean",
    "Fwd Packet Length Mean",
    "Flow IAT Std",
    "Fwd IAT Total",
    "Flow IAT Max",
    "Bwd Packet Length Std",
    "Bwd Packet Length Mean"
]

X = data[features]
y = data["Label"]


# חלוקה ל־70% אימון ו־30% בדיקה
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)


# נרמול Z-score
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


# פונקציה לחישוב False Alarm Rate
def calculate_far(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
    return fp / (fp + tn)


# המודלים שנבדקים
models = {
    "Naive Bayes": GaussianNB(),

    "Logistic Regression": LogisticRegression(max_iter=1000),

    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        max_depth=10,
        random_state=42
    ),

    "XGBoost": XGBClassifier(
        n_estimators=200,
        max_depth=5,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42
    )
}


# אימון ובדיקה
results = []

for model_name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)
    precision = precision_score(y_test, predictions, average="weighted")
    recall = recall_score(y_test, predictions, average="weighted")
    f1 = f1_score(y_test, predictions, average="weighted")
    far = calculate_far(y_test, predictions)

    results.append({
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1,
        "False Alarm Rate": far
    })


# הצגת תוצאות מסודרת
results_table = pd.DataFrame(results)
results_table = results_table.sort_values(by="Accuracy", ascending=False)

print("\nFinal Results:")
print(results_table.to_string(index=False))


# הצגת המודל הטוב ביותר
best_model = results_table.iloc[0]

print("\nBest Model:")
print(best_model["Model"])

print("\nBest Accuracy:")
print(round(best_model["Accuracy"] * 100, 2), "%")



